In [1]:
import pandas as pd


channel =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/channelInfo.csv')
video =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/videoInfo.csv')
display(channel.head())
display(video.head())

,channelid,subcnt,viewcnt,videocnt,ct,channelname
0,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,410238653,736,2021-09-30 03:01:03,꽈뚜룹
1,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,736,2021-09-30 09:01:03,꽈뚜룹
2,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,735,2021-09-30 15:01:03,꽈뚜룹
3,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,737,2021-09-30 21:01:03,꽈뚜룹
4,UCkQCwnkQfgSuPTTnw_Y7v7w,1320000,412531322,737,2021-10-01 03:01:04,꽈뚜룹

,videopk,viewcnt,likecnt,dislikecnt,favoritecnt,cmcnt,ct,videoname
0,c5JQp6xafqc,1667010,30474,706,0,6587,2021-10-10 15:20:03,공범 EP1
1,c5JQp6xafqc,1669089,30495,707,0,6589,2021-10-10 15:30:03,공범 EP1
2,c5JQp6xafqc,1674759,30522,711,0,6596,2021-10-10 15:40:02,공범 EP1
3,c5JQp6xafqc,1677026,30555,712,0,6604,2021-10-10 15:50:03,공범 EP1
4,c5JQp6xafqc,1681824,30585,713,0,6600,2021-10-10 16:00:03,공범 EP1

## Q1.각 데이터의 ‘ct’컬럼을 시간으로 인식할수 있게 datatype을 변경하고 video 데이터의 videoname의 각 value 마다 몇개의 데이터씩 가지고 있는지 확인하라

In [4]:
## datatype  변경
channel['ct'] = pd.to_datetime(channel['ct'])
## videoname value 확인
video.videoname.value_counts()

 공범 EP1    3492
 공범 EP2    3204
 공범 EP3    2568
 공범 EP4    2280
 공범 EP5    1562
 공범 EP6    1274
 공범 EP7     555
 공범 EP8     266
Name: videoname, dtype: int64

## Q2. 수집된 각 video의 가장 최신화 된 날짜의 viewcount값을 출력하라

In [10]:
answer = video.sort_values(['videoname', 'ct']).drop_duplicates('videoname', keep = 'last')[['viewcnt', 'videoname', 'ct']].reset_index(drop = True)
display(answer)

   viewcnt videoname                   ct
0  3180532    공범 EP1  2021-11-01 15:30:03
1  2199328    공범 EP2  2021-11-01 15:30:03
2  1671294    공범 EP3  2021-11-01 15:30:03
3  1818493    공범 EP4  2021-11-01 15:30:03
4  1503435    공범 EP5  2021-11-01 15:30:04
5  1750222    공범 EP6  2021-11-01 15:30:04
6  1630200    공범 EP7  2021-11-01 15:30:05
7  1289088    공범 EP8  2021-11-01 15:30:05

## Q3. Channel 데이터중 2021-10-03일 이후 각 채널의 처음 기록 됐던 구독자 수(subcnt)를 출력하라

In [11]:
channel

,channelid,subcnt,viewcnt,videocnt,ct,channelname
0,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,410238653,736,2021-09-30 03:01:03,꽈뚜룹
1,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,736,2021-09-30 09:01:03,꽈뚜룹
2,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,735,2021-09-30 15:01:03,꽈뚜룹
3,UCkQCwnkQfgSuPTTnw_Y7v7w,1310000,412531322,737,2021-09-30 21:01:03,꽈뚜룹
4,UCkQCwnkQfgSuPTTnw_Y7v7w,1320000,412531322,737,2021-10-01 03:01:04,꽈뚜룹
...,...,...,...,...,...,...
1390,UCbBzKnCYcG7E3EIkSTdsawA,56700,7528614,57,2021-10-31 15:01:04,Balming Tiger
1391,UCbBzKnCYcG7E3EIkSTdsawA,56700,7528614,57,2021-10-31 21:01:04,Balming Tiger
1392,UCbBzKnCYcG7E3EIkSTdsawA,56800,7528614,57,2021-11-01 03:01:03,Balming Tiger
1393,UCbBzKnCYcG7E3EIkSTdsawA,56800,7539876,57,2021-11-01 09:01:04,Balming Tiger
1394,UCbBzKnCYcG7E3EIkSTdsawA,56800,7539876,57,2021-11-01 15:01:07,Balming Tiger

In [17]:
channel.ct = pd.to_datetime(channel.ct)
target = channel[channel.ct >= pd.to_datetime('2021-10-03')].sort_values(['ct','channelname']).drop_duplicates('channelname')
answer = target[['channelname','subcnt']].reset_index(drop=True)
display(answer)

        channelname   subcnt
0            논리왕 전기   922000
1             야전삽짱재   257000
2        츄정ChuJeong   322000
3        김농밀의 농밀한 삶     7520
4       릴펄 Lilpearl    10100
5   와글와글 WagleWagle    55000
6               조나단   215000
7           형사!탐정되다    14900
8     Balming Tiger    54300
9     곽토리 kwak tori   471000
10              꽈뚜룹  1330000

## Q4. 각채널의 2021-10-03 03:00:00 ~ 2021-11-01 15:00:00 까지 구독자수 (subcnt) 의 증가량을 구하여라

In [18]:
channel.ct = pd.to_datetime(channel.ct)
target = channel[channel.ct >= pd.to_datetime('2021-10-03 03:00:00') & channel.ct <= pd.to_datetime('2021-11-01 15:00:00')].sort_values(['ct','channelname']).drop_duplicates('channelname')
target

TypeError: unsupported operand type(s) for &: 'Timestamp' and 'DatetimeArray'