In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv', index_col = 0)
df.head()

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01

## Q1. 인기 동영상 제작 횟수가 많은 채널 상위 10개명 출력 (날짜기준, 중복 포함)

In [2]:
answer = list(df.loc[df.channelId.isin(df.channelId.value_counts().head(10).index)].channelTitle.unique())
answer

['장삐쭈',
 '총몇명',
 '파뿌리',
 '짤툰',
 '런닝맨 - 스브스 공식 채널',
 '엠뚜루마뚜루 : MBC 공식 종합 채널',
 'SPOTV',
 '채널 십오야',
 '이과장',
 'BANGTANTV']

## Q2. dislikes 수가 like 수보다 높은 동영상 제작 채널 모두 출력

In [3]:
answer2 = list(df.loc[df.likes<df.dislikes].channelTitle.unique())
answer2

['핫도그TV',
 'ASMR 애정TV',
 '하얀트리HayanTree',
 '양팡 YangPang',
 '철구형 (CHULTUBE)',
 '왜냐맨하우스',
 '(MUTUBE)와꾸대장봉준',
 '오메킴TV',
 '육지담',
 'MapleStory_KR',
 'ROAD FIGHTING CHAMPIONSHIP',
 '사나이 김기훈',
 '나혼자산다 STUDIO',
 'Gen.G esports']

## Q3. 채널명 바꾼 케이스의 개수

In [4]:
df

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01
...,...,...,...,...,...,...,...,...,...
60394,*풀코스로 먹습니다* 🍗치킨 + 🍕피자 + 🥧디저트,공룡,22,538190,16671,209,3117,UCWf4QKgnTyvmehcRqw-JldQ,2021-10-19
60395,[놀면 뭐하니? 예고] 우린 깐부잖아🦑 놀뭐에 등장한 월드클래스 초대손님!! MBC...,놀면 뭐하니?,24,1607562,14615,258,1141,UCx6jsZ02B4K3SECUrkgPyzg,2021-10-19
60396,먹방 전쟁 : 사랑스러War (feat. 401 정육식당),김종국 GYM JONG KOOK,17,1125911,26490,263,1915,UCoe-0EVDJnjlSoPK8ygcGwQ,2021-10-19
60397,＂너.. 광수지?＂ 협상에 거짓말부터 던지는 광수 닮은꼴 김연경 선수 [런닝맨|21...,스브스 예능맛집,24,1741773,14994,304,802,UCnx4Fi4cmkLGDiFfZ311wWw,2021-10-19
60398,ENHYPEN (엔하이픈) 'Tamed-Dashed' Official MV,HYBE LABELS,10,13753485,1784532,9737,195461,UC3IZKseVpdzPSBaWxBxundA,2021-10-19

In [5]:
## 난 title이랑 id 다른거 출력하려고 했는데 생각해보니까 모든 칼럼이 다르다
## 답에서는 중복을 제거 한 후 제거된 id의 개수를 세어본다

In [6]:
change = df[['channelTitle', 'channelId']].drop_duplicates().channelId.value_counts()
change

UCtQYhzJWFai1y30UIA3uwYQ    3
UC98TOxKQk4aLcx0EjIK0LkQ    3
UC4nEQI74rZkFKlUSwi0ur4A    2
UCn64fSqF2l4rkkjtQUpku2A    2
UCjO3ji06DxmTM1RrzLVwmkA    2
                           ..
UCuZu8NrpBG4WPXRi-hPBl-A    1
UCDrAR1OWC2MD4s0JLetN0MA    1
UCx2MVBsdTJ_sv0LiUpSQU2Q    1
UCu2R3TCLSxYV8pRyBGNOh2g    1
UCRCK5FCJtomQT3b88jXI_DA    1
Name: channelId, Length: 1770, dtype: int64

In [7]:
## 제거된 id의 수가 1보다 많다면 그건 id가 바뀐 채널이라는 뜻이다

In [8]:
change[change>1]

UCtQYhzJWFai1y30UIA3uwYQ    3
UC98TOxKQk4aLcx0EjIK0LkQ    3
UC4nEQI74rZkFKlUSwi0ur4A    2
UCn64fSqF2l4rkkjtQUpku2A    2
UCjO3ji06DxmTM1RrzLVwmkA    2
                           ..
UCk5bhZYNtbPJyNLRxN8D8NQ    2
UCSiGNrrL2lAc0-_MfcUUUHA    2
UCiBKp3KgsQCYT9Z2XxdBpbQ    2
UCUEX0L7GHPs95m8S7G6kWVA    2
UC-IYpdOqjkER7B6cnChwlhA    2
Name: channelId, Length: 71, dtype: int64

In [9]:
target = change[change>1]
print(len(target))

71

## Q4. 일요일에 인기 있었던 영상들 중 가장 많은 영상 종류(categoryId)

In [10]:
df.trending_date2

0        2021-01-01
1        2021-01-01
2        2021-01-01
3        2021-01-01
4        2021-01-01
            ...
60394    2021-10-19
60395    2021-10-19
60396    2021-10-19
60397    2021-10-19
60398    2021-10-19
Name: trending_date2, Length: 60399, dtype: object

In [11]:
## 시간정보가 있는 열을 datetime 자료형으로 변환

In [12]:
df['trending_date2'] = pd.to_datetime(df['trending_date2'])

In [13]:
df['weekday'] = df['trending_date2'].dt.weekday

In [14]:
answer4 = df.loc[df.weekday == 0].categoryId.value_counts().index[0]
answer4

24

## Q5. 각 요일별 인기 영상들의 categoryId는 각각 몇개씩인지 하나의 데이터프레임으로 표현

In [15]:
df

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2,weekday
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01,4
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01,4
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01,4
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01,4
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01,4
...,...,...,...,...,...,...,...,...,...,...
60394,*풀코스로 먹습니다* 🍗치킨 + 🍕피자 + 🥧디저트,공룡,22,538190,16671,209,3117,UCWf4QKgnTyvmehcRqw-JldQ,2021-10-19,1
60395,[놀면 뭐하니? 예고] 우린 깐부잖아🦑 놀뭐에 등장한 월드클래스 초대손님!! MBC...,놀면 뭐하니?,24,1607562,14615,258,1141,UCx6jsZ02B4K3SECUrkgPyzg,2021-10-19,1
60396,먹방 전쟁 : 사랑스러War (feat. 401 정육식당),김종국 GYM JONG KOOK,17,1125911,26490,263,1915,UCoe-0EVDJnjlSoPK8ygcGwQ,2021-10-19,1
60397,＂너.. 광수지?＂ 협상에 거짓말부터 던지는 광수 닮은꼴 김연경 선수 [런닝맨|21...,스브스 예능맛집,24,1741773,14994,304,802,UCnx4Fi4cmkLGDiFfZ311wWw,2021-10-19,1
60398,ENHYPEN (엔하이픈) 'Tamed-Dashed' Official MV,HYBE LABELS,10,13753485,1784532,9737,195461,UC3IZKseVpdzPSBaWxBxundA,2021-10-19,1

In [16]:
group = df.groupby([df['trending_date2'].dt.day_name(), 'categoryId'], as_index = False).size() 
                                                                    #as_index 이 그룹을 인덱스로 지정할 것인가
group

    trending_date2  categoryId  size
0           Friday           1   243
1           Friday           2   120
2           Friday          10   833
3           Friday          15   187
4           Friday          17   633
..             ...         ...   ...
100      Wednesday          25   468
101      Wednesday          26   385
102      Wednesday          27   212
103      Wednesday          28   165
104      Wednesday          29    12

[105 rows x 3 columns]

In [17]:
answer5 = group.pivot(index = 'categoryId', columns = 'trending_date2')
display(answer5)

                 size
trending_date2 Friday Monday Saturday Sunday Thursday Tuesday Wednesday
categoryId
1                 243    263      255    274      246     257       234
2                 120    105      119     99      128     119       129
10                833    837      776    830      890     894       917
15                187    215      198    217      207     208       207
17                633    668      592    636      682     708       706
19                 90     92       87     91       92      89        85
20                283    298      296    289      282     285       291
22               1288   1373     1289   1337     1341    1375      1333
23                568    594      570    556      560     569       566
24               2976   3148     3066   3096     2954    3084      3090
25                444    453      422    437      470     452       468
26                369    378      364    363      375     394       385
27                183    205      183    199      194     194       212
28                171    160      173    167      166     161       165
29                 12     10       10      9       13      11        12

## Q6. viewcount 대비 댓글 수 가 가장 높은 영상 확인 ( view_count 값이 0 인 경우 제외)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60399 entries, 0 to 60398
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           60399 non-null  object
 1   channelTitle    60399 non-null  object
 2   categoryId      60399 non-null  int64
 3   view_count      60399 non-null  int64
 4   likes           60399 non-null  int64
 5   dislikes        60399 non-null  int64
 6   comment_count   60399 non-null  int64
 7   channelId       60399 non-null  object
 8   trending_date2  60399 non-null  datetime64[ns]
 9   weekday         60399 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(3)
memory usage: 5.1+ MB

In [19]:
df2 = df.loc[df.view_count != 0]

In [20]:
df2['ratio'] = (df2['comment_count'] / df2['view_count']).dropna()
result = df2.sort_values(by = 'ratio', ascending = False).iloc[0].title
result

C:\anaconda\envs\silcream\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

'60분 동안 댓글이 달리지 않으면, 영상이 삭제됩니다. (챌린지)'

## Q8. like 대비 dislike 의 수가 가장 적은 영상은? 0인 경우 제외**

In [21]:
df3 = df.loc[df.likes & df.dislikes != 0]
df3

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2,weekday
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01,4
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01,4
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01,4
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01,4
5,"(EN/CN/ID) 월드스타 한 분 더 모셨습니다. 비x박진영 & 싸이, 비주얼 가...",시즌비시즌 Season B Season,24,1274464,26660,368,2701,UCZf4ZESHAIuRtZ-eoMSL97A,2021-01-01,4
...,...,...,...,...,...,...,...,...,...,...
60394,*풀코스로 먹습니다* 🍗치킨 + 🍕피자 + 🥧디저트,공룡,22,538190,16671,209,3117,UCWf4QKgnTyvmehcRqw-JldQ,2021-10-19,1
60395,[놀면 뭐하니? 예고] 우린 깐부잖아🦑 놀뭐에 등장한 월드클래스 초대손님!! MBC...,놀면 뭐하니?,24,1607562,14615,258,1141,UCx6jsZ02B4K3SECUrkgPyzg,2021-10-19,1
60396,먹방 전쟁 : 사랑스러War (feat. 401 정육식당),김종국 GYM JONG KOOK,17,1125911,26490,263,1915,UCoe-0EVDJnjlSoPK8ygcGwQ,2021-10-19,1
60397,＂너.. 광수지?＂ 협상에 거짓말부터 던지는 광수 닮은꼴 김연경 선수 [런닝맨|21...,스브스 예능맛집,24,1741773,14994,304,802,UCnx4Fi4cmkLGDiFfZ311wWw,2021-10-19,1
60398,ENHYPEN (엔하이픈) 'Tamed-Dashed' Official MV,HYBE LABELS,10,13753485,1784532,9737,195461,UC3IZKseVpdzPSBaWxBxundA,2021-10-19,1

In [22]:
num = (df3['dislikes'] / df3['likes']).sort_values().index[0]
result = df.iloc[num].title ## df3  가 아닌 df 였다는점!!

In [23]:
result

'[줌터뷰] *최초공개* 사부작즈🐰🐶의 비공식 이름은 아이라인즈? 꿀조합 티키타카 가득한 NCT 127 도영&정우의 줌터뷰'

## Q9. 가장 많은 트렌드 영상을 제작한 채널의 이름은? (날짜 기준, 중복 포함)

In [24]:
change = df[['trending_date2', 'channelId']].drop_duplicates().channelId.value_counts()
change ##실패

UCszFjh7CEfwDb7UUGb4RzCQ    219
UClzB2iZ5jPoTNz0S-QU6Wiw    218
UChbE5OZQ6dRHECsX0tEPEZQ    194
UCaKod3X1Tn4c7Ci0iUKcvzQ    192
UCwx6n_4OcLgzAGdty0RWCoA    189
                           ...
UCj00eA-Q0lokXCA6JAa_grw      1
UCCOG5mtQZIdndAVQ8km3zQg      1
UCdtY7-_h-KgBTXHJfTk8wwQ      1
UCESC_GRUe4Z7-OOxk_AWm5Q      1
UCNh_yWrspnQbZDZijQFyjbw      1
Name: channelId, Length: 1770, dtype: int64

In [25]:
answer9 = df.loc[df.channelId == df.channelId.value_counts().index[0]].channelTitle.unique()[0]
answer9

'짤툰'

## Q10. 2일 이상 인기동영상 리스트에 포함된 동영상의 숫자?

In [26]:
answer10 = (df[['title', 'channelId']].value_counts()>=20).sum()
answer10

40